# Generated by Django 4.2.6 on 2023-10-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swift', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='author',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
